### ISSUE TITLE
#2- Research Chosen Areas

### ISSUE THREAD

**Issue by ESinclair81** [SterlynKong/Freebiez#2]
- Sterlyn- Multer and related material
- Eon- Layout options both framework and design 
- Shama- General overview ideas

**Comment by Shamakhan786** [comment]
javascript HTML CSS

**Comment by SterlynKong** [comment]
https://helicaltech.com/save-image-mysql-display-using-nodejs-sequelizejs/

I think I can try to follow this write-up to try to implement the storage of images to DB and recall them as well. I am still reading through it.
