### ISSUE TITLE
Store images to DB and Recall them when needed

### ISSUE THREAD

**Issue by SterlynKong** [SterlynKong/Freebiez#3]
**MULTER**

[Implement MULTER for image storage and retrieval](https://helicaltech.com/save-image-mysql-display-using-nodejs-sequelizejs/)

I think I can try to follow this write-up to try to implement the storage of images to DB and recall them as well. I am still reading through it.

**Comment by ESinclair81** [comment]
Nice find, it reads in a logical way

**Comment by SterlynKong** [comment]
I have now been able to store images in the db as well as posts and they can reference each other.
